In [3]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy.fft import fft, fftfreq

In [4]:
File_data = []

In [5]:
for i in range(0,17045,1):
    data = np.loadtxt('Apnea-ecg/ecg segments/train/'+str(i)+'/raw_ecg_segment_data.txt',skiprows=2,usecols=0)
    File_data.append(data)


In [6]:
print(len(File_data))
print(len(File_data[0]))
print(File_data[0])

17045
6000
[-0.06  -0.065 -0.06  ...  0.04   0.07   0.09 ]


In [7]:
import wfdb
annotation = []
for i in range(1,21):
    s = ''
    if( i < 10):
        s = '0'
    data = wfdb.rdann("apnea-ecg-database-1.0.0/a"+s+str(i), extension="apn")
    annotation.append(data.symbol)

for i in range(1,6):
    s = ''
    if( i < 10):
        s = '0'
    data = wfdb.rdann("apnea-ecg-database-1.0.0/b"+s+str(i), extension="apn")
    annotation.append(data.symbol)

for i in range(1,11):
    s = ''
    if( i < 10):
        s = '0'
    data = wfdb.rdann("apnea-ecg-database-1.0.0/c"+s+str(i), extension="apn")
    annotation.append(data.symbol)

In [8]:
print(len(annotation))
print(len(annotation[0]))

35
489


In [9]:
annotation

[['N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'N',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',
  'A',

In [10]:
File_data

[array([-0.06 , -0.065, -0.06 , ...,  0.04 ,  0.07 ,  0.09 ]),
 array([ 0.14 ,  0.17 ,  0.215, ..., -0.11 , -0.095, -0.1  ]),
 array([-0.1  , -0.105, -0.105, ..., -0.04 , -0.055, -0.11 ]),
 array([-0.06 , -0.085, -0.085, ..., -0.01 ,  0.03 ,  0.02 ]),
 array([0.025, 0.03 , 0.1  , ..., 0.05 , 0.07 , 0.115]),
 array([ 0.155,  0.19 ,  0.225, ..., -0.015, -0.02 , -0.02 ]),
 array([-0.03 , -0.035, -0.035, ..., -0.19 , -0.24 ,  0.015]),
 array([ 0.725,  1.345,  0.785, ..., -0.825, -0.525, -0.24 ]),
 array([-0.15 , -0.155, -0.17 , ..., -0.085, -0.08 , -0.1  ]),
 array([-0.085, -0.09 , -0.085, ..., -0.025, -0.08 , -0.195]),
 array([-0.175, -0.195, -0.18 , ...,  0.09 ,  0.12 ,  0.18 ]),
 array([0.21 , 0.235, 0.235, ..., 0.205, 0.23 , 0.255]),
 array([ 0.24 ,  0.28 ,  0.25 , ..., -0.055, -0.06 , -0.06 ]),
 array([-0.065, -0.08 , -0.09 , ..., -0.055, -0.05 , -0.035]),
 array([-0.02 , -0.06 , -0.045, ...,  0.12 ,  0.02 , -0.005]),
 array([-0.035, -0.1  , -0.2  , ...,  0.22 ,  0.26 ,  0.23 ]),
 arr

In [11]:
FEATURES = ['MIN','MAX','MEAN','RMS','VAR','STD','POWER','PEAK','P2P','CREST FACTOR','SKEW','KURTOSIS',
            'MAX_f','SUM_f','MEAN_f','VAR_f','PEAK_f','SKEW_f','KURTOSIS_f']

In [12]:
Min=[];Max=[];Mean=[];Rms=[];Var=[];Std=[];Power=[];Peak=[];Skew=[];Kurtosis=[];P2p=[];CrestFactor=[]
FormFactor=[]; PulseIndicator=[]
Max_f=[];Sum_f=[];Mean_f=[];Var_f=[];Peak_f=[];Skew_f=[];Kurtosis_f=[]

In [13]:
for i in range(len(File_data)):
    X = File_data[i]
    ## TIME DOMAIN ##

    Min.append(np.min(X))
    Max.append(np.max(X))
    Mean.append(np.mean(X))
    Rms.append(np.sqrt(np.mean(X**2)))
    Var.append(np.var(X))
    Std.append(np.std(X))
    Power.append(np.mean(X**2))
    Peak.append(np.max(np.abs(X)))
    P2p.append(np.ptp(X))
    CrestFactor.append(np.max(np.abs(X))/np.sqrt(np.mean(X**2)))
    Skew.append(stats.skew(X))
    Kurtosis.append(stats.kurtosis(X))
    FormFactor.append(np.sqrt(np.mean(X**2))/np.mean(X))
    PulseIndicator.append(np.max(np.abs(X))/np.mean(X))
    ## FREQ DOMAIN ##
    ft = fft(X)
    S = np.abs(ft**2)/len(X)
    Max_f.append(np.max(S))
    Sum_f.append(np.sum(S))
    Mean_f.append(np.mean(S))
    Var_f.append(np.var(S))
    
    Peak_f.append(np.max(np.abs(S)))
    Skew_f.append(stats.skew(X))
    Kurtosis_f.append(stats.kurtosis(X))

C:\Users\Eng. Shuaib Saleh\AppData\Local\Temp\ipykernel_22756\2219737245.py:15: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  Skew.append(stats.skew(X))
C:\Users\Eng. Shuaib Saleh\AppData\Local\Temp\ipykernel_22756\2219737245.py:16: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  Kurtosis.append(stats.kurtosis(X))
C:\Users\Eng. Shuaib Saleh\AppData\Local\Temp\ipykernel_22756\2219737245.py:28: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  Skew_f.append(stats.skew(X))
C:\Users\Eng. Shuaib Saleh\AppData\Local\Temp\ipykernel_22756\2219737245.py:29: RuntimeWarning: Precision loss occurred in moment calculation due to c

In [ ]:
df_features = pd.DataFrame(index = [FEATURES], 
                            data = [Min,Max,Mean,Rms,Var,Std,Power,Peak,P2p,CrestFactor,Skew,Kurtosis,
                                    Max_f,Sum_f,Mean_f,Var_f,Peak_f,Skew_f,Kurtosis_f])

df_features = df_features.transpose()

In [ ]:
df_features

MIN    MAX      MEAN       RMS       VAR       STD     POWER   PEAK  \
0     -0.885  1.750 -0.000919  0.255152  0.065102  0.255151  0.065103  1.750   
1     -0.900  1.740  0.000766  0.268868  0.072289  0.268866  0.072290  1.740   
2     -1.035  1.750  0.000017  0.271984  0.073975  0.271984  0.073975  1.750   
3     -1.170  1.845 -0.000441  0.281248  0.079100  0.281247  0.079100  1.845   
4     -1.035  1.700  0.000551  0.267258  0.071427  0.267258  0.071427  1.700   
...      ...    ...       ...       ...       ...       ...       ...    ...   
17040 -0.845  1.255  0.004649  0.172141  0.029611  0.172079  0.029633  1.255   
17041 -0.385  1.015  0.001453  0.139884  0.019565  0.139876  0.019568  1.015   
17042 -0.370  1.040  0.002123  0.146720  0.021522  0.146705  0.021527  1.040   
17043 -0.410  1.145  0.004647  0.151157  0.022827  0.151085  0.022848  1.145   
17044 -2.980  2.705 -0.007913  0.193800  0.037496  0.193638  0.037558  2.980   

         P2P CREST FACTOR      SKEW   KURTOSIS     MAX_f       SUM_f  \
0      2.635     6.858649  2.823821  16.244233  1.621756  390.616125   
1      2.640     6.471587  2.682191  14.860631  3.978534  433.738675   
2      2.785     6.434194  2.486454  14.055261  1.750031  443.852850   
3      3.015     6.560052  1.920162  11.388732  1.727392  474.601875   
4      2.735     6.360887  2.111700  11.644186  3.358612  428.562025   
...      ...          ...       ...        ...       ...         ...   
17040  2.100     7.290516  2.806774  14.685007  1.120043  177.796075   
17041  1.400     7.256014  4.394558  24.685164  1.103616  117.405150   
17042  1.410     7.088323  3.968774  21.390985  2.140504  129.160850   
17043  1.555     7.574924  3.926939  20.668036  0.850997  137.089975   
17044  5.685    15.376670  1.916688  37.851586  1.432485  187.792375   

         MEAN_f     VAR_f    PEAK_f    SKEW_f KURTOSIS_f  
0      0.065103  0.019873  1.621756  2.823821  16.244233  
1      0.072290  0.025240  3.978534  2.682191  14.860631  
2      0.073975  0.021393  1.750031  2.486454  14.055261  
3      0.079100  0.024153  1.727392  1.920162  11.388732  
4      0.071427  0.025818  3.358612  2.111700  11.644186  
...         ...       ...       ...       ...        ...  
17040  0.029633  0.004459  1.120043  2.806774  14.685007  
17041  0.019568  0.002947  1.103616  4.394558  24.685164  
17042  0.021527  0.004486  2.140504  3.968774  21.390985  
17043  0.022848  0.002578  0.850997  3.926939  20.668036  
17044  0.037558  0.005697  1.432485  1.916688  37.851586  

[17045 rows x 19 columns]

In [ ]:
df_features.to_csv("Features.csv")

In [ ]:
# flat_File_data = [item for sublist in File_data for item in sublist]

In [ ]:
# print(len(flat_File_data))
# print(flat_File_data[0])

102187500
-0.06


In [ ]:
flat_annotation = [item for sublist in annotation for item in sublist]

NameError: name 'annotation' is not defined

In [ ]:
print(len(flat_annotation))
print(flat_annotation)

17045